// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: server/api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxnState int32

const (
	TxnState_TXN_STATE_UNKNOWN   TxnState = 0
	TxnState_TXN_STATE_ACCEPTED  TxnState = 1
	TxnState_TXN_STATE_COMMITTED TxnState = 2
	TxnState_TXN_STATE_EXECUTED  TxnState = 3
)

// Enum value maps for TxnState.
var (
	TxnState_name = map[int32]string{
		0: "TXN_STATE_UNKNOWN",
		1: "TXN_STATE_ACCEPTED",
		2: "TXN_STATE_COMMITTED",
		3: "TXN_STATE_EXECUTED",
	}
	TxnState_value = map[string]int32{
		"TXN_STATE_UNKNOWN":   0,
		"TXN_STATE_ACCEPTED":  1,
		"TXN_STATE_COMMITTED": 2,
		"TXN_STATE_EXECUTED":  3,
	}
)

func (x TxnState) Enum() *TxnState {
	p := new(TxnState)
	*p = x
	return p
}

func (x TxnState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxnState) Descriptor() protoreflect.EnumDescriptor {
	return file_server_api_api_proto_enumTypes[0].Descriptor()
}

func (TxnState) Type() protoreflect.EnumType {
	return &file_server_api_api_proto_enumTypes[0]
}

func (x TxnState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxnState.Descriptor instead.
func (TxnState) EnumDescriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{0}
}

type ReadOnlyPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ReadOnlyPayload) Reset() {
	*x = ReadOnlyPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadOnlyPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOnlyPayload) ProtoMessage() {}

func (x *ReadOnlyPayload) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOnlyPayload.ProtoReflect.Descriptor instead.
func (*ReadOnlyPayload) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *ReadOnlyPayload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ReadOnlyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found bool   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ReadOnlyResponse) Reset() {
	*x = ReadOnlyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadOnlyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOnlyResponse) ProtoMessage() {}

func (x *ReadOnlyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOnlyResponse.ProtoReflect.Descriptor instead.
func (*ReadOnlyResponse) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *ReadOnlyResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ReadOnlyResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ReadOnlyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type IntraShardRWPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value  []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Delete bool   `protobuf:"varint,3,opt,name=delete,proto3" json:"delete,omitempty"`
}

func (x *IntraShardRWPayload) Reset() {
	*x = IntraShardRWPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntraShardRWPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntraShardRWPayload) ProtoMessage() {}

func (x *IntraShardRWPayload) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntraShardRWPayload.ProtoReflect.Descriptor instead.
func (*IntraShardRWPayload) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *IntraShardRWPayload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *IntraShardRWPayload) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *IntraShardRWPayload) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

type IntraShardRWResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found bool   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *IntraShardRWResp) Reset() {
	*x = IntraShardRWResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntraShardRWResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntraShardRWResp) ProtoMessage() {}

func (x *IntraShardRWResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntraShardRWResp.ProtoReflect.Descriptor instead.
func (*IntraShardRWResp) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *IntraShardRWResp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *IntraShardRWResp) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *IntraShardRWResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InterShardRWPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value  []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Delete bool   `protobuf:"varint,3,opt,name=delete,proto3" json:"delete,omitempty"`
}

func (x *InterShardRWPayload) Reset() {
	*x = InterShardRWPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterShardRWPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterShardRWPayload) ProtoMessage() {}

func (x *InterShardRWPayload) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterShardRWPayload.ProtoReflect.Descriptor instead.
func (*InterShardRWPayload) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{4}
}

func (x *InterShardRWPayload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *InterShardRWPayload) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *InterShardRWPayload) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

type InterShardRWResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found bool   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *InterShardRWResp) Reset() {
	*x = InterShardRWResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterShardRWResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterShardRWResp) ProtoMessage() {}

func (x *InterShardRWResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterShardRWResp.ProtoReflect.Descriptor instead.
func (*InterShardRWResp) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{5}
}

func (x *InterShardRWResp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *InterShardRWResp) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *InterShardRWResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender    int32  `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver  int32  `protobuf:"varint,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount    int32  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp int64  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientId  string `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{6}
}

func (x *Message) GetSender() int32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *Message) GetReceiver() int32 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *Message) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BallotVal int32  `protobuf:"varint,1,opt,name=ballot_val,json=ballotVal,proto3" json:"ballot_val,omitempty"`
	ServerId  int32  `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Timestamp int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientId  string `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Result    bool   `protobuf:"varint,5,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{7}
}

func (x *Reply) GetBallotVal() int32 {
	if x != nil {
		return x.BallotVal
	}
	return 0
}

func (x *Reply) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *Reply) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Reply) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Reply) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type LogRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqNum      int32 `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	BallotVal   int32 `protobuf:"varint,2,opt,name=ballot_val,json=ballotVal,proto3" json:"ballot_val,omitempty"`
	ServerId    int32 `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Sender      int32 `protobuf:"varint,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver    int32 `protobuf:"varint,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount      int32 `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp   int64 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsCommitted bool  `protobuf:"varint,8,opt,name=is_committed,json=isCommitted,proto3" json:"is_committed,omitempty"`
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{8}
}

func (x *LogRecord) GetSeqNum() int32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *LogRecord) GetBallotVal() int32 {
	if x != nil {
		return x.BallotVal
	}
	return 0
}

func (x *LogRecord) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *LogRecord) GetSender() int32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *LogRecord) GetReceiver() int32 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *LogRecord) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LogRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogRecord) GetIsCommitted() bool {
	if x != nil {
		return x.IsCommitted
	}
	return false
}

type AcceptResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NodeId  int32      `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Record  *LogRecord `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *AcceptResp) Reset() {
	*x = AcceptResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResp) ProtoMessage() {}

func (x *AcceptResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResp.ProtoReflect.Descriptor instead.
func (*AcceptResp) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{9}
}

func (x *AcceptResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AcceptResp) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *AcceptResp) GetRecord() *LogRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type Blank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Blank) Reset() {
	*x = Blank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blank) ProtoMessage() {}

func (x *Blank) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blank.ProtoReflect.Descriptor instead.
func (*Blank) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{10}
}

type PrepareReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BallotVal int32 `protobuf:"varint,1,opt,name=ballot_val,json=ballotVal,proto3" json:"ballot_val,omitempty"`
	ServerId  int32 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *PrepareReq) Reset() {
	*x = PrepareReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareReq) ProtoMessage() {}

func (x *PrepareReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareReq.ProtoReflect.Descriptor instead.
func (*PrepareReq) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{11}
}

func (x *PrepareReq) GetBallotVal() int32 {
	if x != nil {
		return x.BallotVal
	}
	return 0
}

func (x *PrepareReq) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type PromiseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success   bool         `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BallotVal int32        `protobuf:"varint,2,opt,name=ballot_val,json=ballotVal,proto3" json:"ballot_val,omitempty"`
	ServerId  int32        `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	AcceptLog []*LogRecord `protobuf:"bytes,4,rep,name=accept_log,json=acceptLog,proto3" json:"accept_log,omitempty"`
}

func (x *PromiseResp) Reset() {
	*x = PromiseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromiseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromiseResp) ProtoMessage() {}

func (x *PromiseResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromiseResp.ProtoReflect.Descriptor instead.
func (*PromiseResp) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{12}
}

func (x *PromiseResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PromiseResp) GetBallotVal() int32 {
	if x != nil {
		return x.BallotVal
	}
	return 0
}

func (x *PromiseResp) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *PromiseResp) GetAcceptLog() []*LogRecord {
	if x != nil {
		return x.AcceptLog
	}
	return nil
}

type NewViewReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BallotVal int32        `protobuf:"varint,1,opt,name=ballot_val,json=ballotVal,proto3" json:"ballot_val,omitempty"`
	ServerId  int32        `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	AcceptLog []*LogRecord `protobuf:"bytes,3,rep,name=accept_log,json=acceptLog,proto3" json:"accept_log,omitempty"`
}

func (x *NewViewReq) Reset() {
	*x = NewViewReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewViewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewReq) ProtoMessage() {}

func (x *NewViewReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewReq.ProtoReflect.Descriptor instead.
func (*NewViewReq) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{13}
}

func (x *NewViewReq) GetBallotVal() int32 {
	if x != nil {
		return x.BallotVal
	}
	return 0
}

func (x *NewViewReq) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *NewViewReq) GetAcceptLog() []*LogRecord {
	if x != nil {
		return x.AcceptLog
	}
	return nil
}

type Logs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logs []*LogRecord `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
}

func (x *Logs) Reset() {
	*x = Logs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Logs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logs) ProtoMessage() {}

func (x *Logs) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logs.ProtoReflect.Descriptor instead.
func (*Logs) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{14}
}

func (x *Logs) GetLogs() []*LogRecord {
	if x != nil {
		return x.Logs
	}
	return nil
}

type Vault struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vault map[string]int32 `protobuf:"bytes,1,rep,name=vault,proto3" json:"vault,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *Vault) Reset() {
	*x = Vault{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vault) ProtoMessage() {}

func (x *Vault) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vault.ProtoReflect.Descriptor instead.
func (*Vault) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{15}
}

func (x *Vault) GetVault() map[string]int32 {
	if x != nil {
		return x.Vault
	}
	return nil
}

type RequestInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqNum int32 `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
}

func (x *RequestInfo) Reset() {
	*x = RequestInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInfo) ProtoMessage() {}

func (x *RequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInfo.ProtoReflect.Descriptor instead.
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{16}
}

func (x *RequestInfo) GetSeqNum() int32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status TxnState `protobuf:"varint,1,opt,name=status,proto3,enum=api.TxnState" json:"status,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{17}
}

func (x *Status) GetStatus() TxnState {
	if x != nil {
		return x.Status
	}
	return TxnState_TXN_STATE_UNKNOWN
}

type ViewLogs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Views []*NewViewReq `protobuf:"bytes,1,rep,name=views,proto3" json:"views,omitempty"`
}

func (x *ViewLogs) Reset() {
	*x = ViewLogs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewLogs) ProtoMessage() {}

func (x *ViewLogs) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewLogs.ProtoReflect.Descriptor instead.
func (*ViewLogs) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{18}
}

func (x *ViewLogs) GetViews() []*NewViewReq {
	if x != nil {
		return x.Views
	}
	return nil
}

var File_server_api_api_proto protoreflect.FileDescriptor

var file_server_api_api_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x23, 0x0a, 0x0f, 0x52,
	0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x54, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f,
	0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x55, 0x0a, 0x13, 0x49, 0x6e, 0x74, 0x72, 0x61, 0x53,
	0x68, 0x61, 0x72, 0x64, 0x52, 0x57, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x22, 0x54, 0x0a,
	0x10, 0x49, 0x6e, 0x74, 0x72, 0x61, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x57, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x55, 0x0a, 0x13, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x52, 0x57, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x22, 0x54, 0x0a, 0x10, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x57, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x90, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x22, 0x96, 0x01, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xed, 0x01, 0x0a,
	0x09, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65,
	0x71, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x71,
	0x4e, 0x75, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x5f, 0x76, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x56,
	0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x69, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x22, 0x67, 0x0a, 0x0a,
	0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a,
	0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x07, 0x0a, 0x05, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x22, 0x48,
	0x0a, 0x0a, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a,
	0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x92, 0x01, 0x0a, 0x0b, 0x50, 0x72, 0x6f,
	0x6d, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x5f, 0x76, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x56, 0x61,
	0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2d,
	0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x09, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4c, 0x6f, 0x67, 0x22, 0x77, 0x0a,
	0x0a, 0x4e, 0x65, 0x77, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x62,
	0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x09, 0x61, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x4c, 0x6f, 0x67, 0x22, 0x2a, 0x0a, 0x04, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x22,
	0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x04, 0x6c, 0x6f,
	0x67, 0x73, 0x22, 0x6e, 0x0a, 0x05, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x2b, 0x0a, 0x05, 0x76,
	0x61, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x05, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x1a, 0x38, 0x0a, 0x0a, 0x56, 0x61, 0x75, 0x6c,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x26, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x71, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x22, 0x2f, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x78, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x31, 0x0a, 0x08, 0x56,
	0x69, 0x65, 0x77, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x65, 0x77,
	0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x52, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x2a, 0x6a,
	0x0a, 0x08, 0x54, 0x78, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x54, 0x58,
	0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x58, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x41,
	0x43, 0x43, 0x45, 0x50, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x54, 0x58, 0x4e,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x54, 0x45, 0x44,
	0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x58, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x45, 0x58, 0x45, 0x43, 0x55, 0x54, 0x45, 0x44, 0x10, 0x03, 0x32, 0xcc, 0x01, 0x0a, 0x02, 0x4b,
	0x56, 0x12, 0x3e, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4f,
	0x6e, 0x6c, 0x79, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x42, 0x0a, 0x0f, 0x49, 0x6e, 0x74, 0x72, 0x61, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52,
	0x57, 0x52, 0x65, 0x71, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x74, 0x72, 0x61,
	0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x57, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x15,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x74, 0x72, 0x61, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52,
	0x57, 0x52, 0x65, 0x73, 0x70, 0x12, 0x42, 0x0a, 0x0f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x52, 0x57, 0x52, 0x65, 0x71, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x57, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x52, 0x57, 0x52, 0x65, 0x73, 0x70, 0x32, 0x37, 0x0a, 0x10, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x78, 0x6e, 0x73, 0x12, 0x23, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x32, 0xb9, 0x01, 0x0a, 0x10, 0x50, 0x61, 0x78, 0x6f, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x12, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x1a, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x24, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x0e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x1a, 0x0a, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x12, 0x2c, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x70,
	0x61, 0x72, 0x65, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x69,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x56, 0x69, 0x65,
	0x77, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x65, 0x77, 0x56, 0x69, 0x65, 0x77, 0x52,
	0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x32, 0xac,
	0x01, 0x0a, 0x0e, 0x50, 0x61, 0x78, 0x6f, 0x73, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x21, 0x0a, 0x08, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x12, 0x0a, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x1a, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4c, 0x6f, 0x67, 0x73, 0x12, 0x21, 0x0a, 0x07, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x44, 0x42, 0x12,
	0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x1a, 0x0a, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x2c, 0x0a, 0x0b, 0x50, 0x72, 0x69, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x26, 0x0a, 0x09, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x56, 0x69,
	0x65, 0x77, 0x12, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x1a, 0x0d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x4c, 0x6f, 0x67, 0x73, 0x42, 0x14, 0x5a,
	0x12, 0x32, 0x50, 0x43, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x3b,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_api_api_proto_rawDescOnce sync.Once
	file_server_api_api_proto_rawDescData = file_server_api_api_proto_rawDesc
)

func file_server_api_api_proto_rawDescGZIP() []byte {
	file_server_api_api_proto_rawDescOnce.Do(func() {
		file_server_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_api_api_proto_rawDescData)
	})
	return file_server_api_api_proto_rawDescData
}

var file_server_api_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_server_api_api_proto_goTypes = []interface{}{
	(TxnState)(0),               // 0: api.TxnState
	(*ReadOnlyPayload)(nil),     // 1: api.ReadOnlyPayload
	(*ReadOnlyResponse)(nil),    // 2: api.ReadOnlyResponse
	(*IntraShardRWPayload)(nil), // 3: api.IntraShardRWPayload
	(*IntraShardRWResp)(nil),    // 4: api.IntraShardRWResp
	(*InterShardRWPayload)(nil), // 5: api.InterShardRWPayload
	(*InterShardRWResp)(nil),    // 6: api.InterShardRWResp
	(*Message)(nil),             // 7: api.Message
	(*Reply)(nil),               // 8: api.Reply
	(*LogRecord)(nil),           // 9: api.LogRecord
	(*AcceptResp)(nil),          // 10: api.AcceptResp
	(*Blank)(nil),               // 11: api.Blank
	(*PrepareReq)(nil),          // 12: api.PrepareReq
	(*PromiseResp)(nil),         // 13: api.PromiseResp
	(*NewViewReq)(nil),          // 14: api.NewViewReq
	(*Logs)(nil),                // 15: api.Logs
	(*Vault)(nil),               // 16: api.Vault
	(*RequestInfo)(nil),         // 17: api.RequestInfo
	(*Status)(nil),              // 18: api.Status
	(*ViewLogs)(nil),            // 19: api.ViewLogs
	nil,                         // 20: api.Vault.VaultEntry
}
var file_server_api_api_proto_depIdxs = []int32{
	9,  // 0: api.AcceptResp.record:type_name -> api.LogRecord
	9,  // 1: api.PromiseResp.accept_log:type_name -> api.LogRecord
	9,  // 2: api.NewViewReq.accept_log:type_name -> api.LogRecord
	9,  // 3: api.Logs.logs:type_name -> api.LogRecord
	20, // 4: api.Vault.vault:type_name -> api.Vault.VaultEntry
	0,  // 5: api.Status.status:type_name -> api.TxnState
	14, // 6: api.ViewLogs.views:type_name -> api.NewViewReq
	1,  // 7: api.KV.ReadOnlyRequest:input_type -> api.ReadOnlyPayload
	3,  // 8: api.KV.IntraShardRWReq:input_type -> api.IntraShardRWPayload
	5,  // 9: api.KV.InterShardRWReq:input_type -> api.InterShardRWPayload
	7,  // 10: api.ClientServerTxns.Request:input_type -> api.Message
	9,  // 11: api.PaxosReplication.Accept:input_type -> api.LogRecord
	9,  // 12: api.PaxosReplication.Commit:input_type -> api.LogRecord
	12, // 13: api.PaxosReplication.Prepare:input_type -> api.PrepareReq
	14, // 14: api.PaxosReplication.NewView:input_type -> api.NewViewReq
	11, // 15: api.PaxosPrintInfo.PrintLog:input_type -> api.Blank
	11, // 16: api.PaxosPrintInfo.PrintDB:input_type -> api.Blank
	17, // 17: api.PaxosPrintInfo.PrintStatus:input_type -> api.RequestInfo
	11, // 18: api.PaxosPrintInfo.PrintView:input_type -> api.Blank
	2,  // 19: api.KV.ReadOnlyRequest:output_type -> api.ReadOnlyResponse
	4,  // 20: api.KV.IntraShardRWReq:output_type -> api.IntraShardRWResp
	6,  // 21: api.KV.InterShardRWReq:output_type -> api.InterShardRWResp
	8,  // 22: api.ClientServerTxns.Request:output_type -> api.Reply
	10, // 23: api.PaxosReplication.Accept:output_type -> api.AcceptResp
	11, // 24: api.PaxosReplication.Commit:output_type -> api.Blank
	13, // 25: api.PaxosReplication.Prepare:output_type -> api.PromiseResp
	11, // 26: api.PaxosReplication.NewView:output_type -> api.Blank
	15, // 27: api.PaxosPrintInfo.PrintLog:output_type -> api.Logs
	16, // 28: api.PaxosPrintInfo.PrintDB:output_type -> api.Vault
	18, // 29: api.PaxosPrintInfo.PrintStatus:output_type -> api.Status
	19, // 30: api.PaxosPrintInfo.PrintView:output_type -> api.ViewLogs
	19, // [19:31] is the sub-list for method output_type
	7,  // [7:19] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_server_api_api_proto_init() }
func file_server_api_api_proto_init() {
	if File_server_api_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_api_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadOnlyPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadOnlyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntraShardRWPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntraShardRWResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterShardRWPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterShardRWResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromiseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewViewReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Logs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vault); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewLogs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_api_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_server_api_api_proto_goTypes,
		DependencyIndexes: file_server_api_api_proto_depIdxs,
		EnumInfos:         file_server_api_api_proto_enumTypes,
		MessageInfos:      file_server_api_api_proto_msgTypes,
	}.Build()
	File_server_api_api_proto = out.File
	file_server_api_api_proto_rawDesc = nil
	file_server_api_api_proto_goTypes = nil
	file_server_api_api_proto_depIdxs = nil
}
