// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: server/api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KVClient is the client API for KV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KVClient interface {
	ReadOnlyRequest(ctx context.Context, in *ReadOnlyPayload, opts ...grpc.CallOption) (*ReadOnlyResponse, error)
	IntraShardRWReq(ctx context.Context, in *IntraShardRWPayload, opts ...grpc.CallOption) (*IntraShardRWResp, error)
	InterShardRWReq(ctx context.Context, in *InterShardRWPayload, opts ...grpc.CallOption) (*InterShardRWResp, error)
}

type kVClient struct {
	cc grpc.ClientConnInterface
}

func NewKVClient(cc grpc.ClientConnInterface) KVClient {
	return &kVClient{cc}
}

func (c *kVClient) ReadOnlyRequest(ctx context.Context, in *ReadOnlyPayload, opts ...grpc.CallOption) (*ReadOnlyResponse, error) {
	out := new(ReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/api.KV/ReadOnlyRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVClient) IntraShardRWReq(ctx context.Context, in *IntraShardRWPayload, opts ...grpc.CallOption) (*IntraShardRWResp, error) {
	out := new(IntraShardRWResp)
	err := c.cc.Invoke(ctx, "/api.KV/IntraShardRWReq", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVClient) InterShardRWReq(ctx context.Context, in *InterShardRWPayload, opts ...grpc.CallOption) (*InterShardRWResp, error) {
	out := new(InterShardRWResp)
	err := c.cc.Invoke(ctx, "/api.KV/InterShardRWReq", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KVServer is the server API for KV service.
// All implementations must embed UnimplementedKVServer
// for forward compatibility
type KVServer interface {
	ReadOnlyRequest(context.Context, *ReadOnlyPayload) (*ReadOnlyResponse, error)
	IntraShardRWReq(context.Context, *IntraShardRWPayload) (*IntraShardRWResp, error)
	InterShardRWReq(context.Context, *InterShardRWPayload) (*InterShardRWResp, error)
	mustEmbedUnimplementedKVServer()
}

// UnimplementedKVServer must be embedded to have forward compatible implementations.
type UnimplementedKVServer struct {
}

func (UnimplementedKVServer) ReadOnlyRequest(context.Context, *ReadOnlyPayload) (*ReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadOnlyRequest not implemented")
}
func (UnimplementedKVServer) IntraShardRWReq(context.Context, *IntraShardRWPayload) (*IntraShardRWResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IntraShardRWReq not implemented")
}
func (UnimplementedKVServer) InterShardRWReq(context.Context, *InterShardRWPayload) (*InterShardRWResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InterShardRWReq not implemented")
}
func (UnimplementedKVServer) mustEmbedUnimplementedKVServer() {}

// UnsafeKVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KVServer will
// result in compilation errors.
type UnsafeKVServer interface {
	mustEmbedUnimplementedKVServer()
}

func RegisterKVServer(s grpc.ServiceRegistrar, srv KVServer) {
	s.RegisterService(&KV_ServiceDesc, srv)
}

func _KV_ReadOnlyRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadOnlyPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServer).ReadOnlyRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.KV/ReadOnlyRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServer).ReadOnlyRequest(ctx, req.(*ReadOnlyPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _KV_IntraShardRWReq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntraShardRWPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServer).IntraShardRWReq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.KV/IntraShardRWReq",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServer).IntraShardRWReq(ctx, req.(*IntraShardRWPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _KV_InterShardRWReq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterShardRWPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServer).InterShardRWReq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.KV/InterShardRWReq",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServer).InterShardRWReq(ctx, req.(*InterShardRWPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// KV_ServiceDesc is the grpc.ServiceDesc for KV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.KV",
	HandlerType: (*KVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadOnlyRequest",
			Handler:    _KV_ReadOnlyRequest_Handler,
		},
		{
			MethodName: "IntraShardRWReq",
			Handler:    _KV_IntraShardRWReq_Handler,
		},
		{
			MethodName: "InterShardRWReq",
			Handler:    _KV_InterShardRWReq_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/api/api.proto",
}
